# Generated by Django 4.2.3 on 2024-12-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sbd', models.IntegerField(primary_key=True, serialize=False)),
                ('toan', models.FloatField(blank=True, null=True)),
                ('ngu_van', models.FloatField(blank=True, null=True)),
                ('ngoai_ngu', models.FloatField(blank=True, null=True)),
                ('vat_ly', models.FloatField(blank=True, null=True)),
                ('hoa_hoc', models.FloatField(blank=True, null=True)),
                ('sinh_hoc', models.FloatField(blank=True, null=True)),
                ('lich_su', models.FloatField(blank=True, null=True)),
                ('dia_ly', models.FloatField(blank=True, null=True)),
                ('ma_ngoai_ngu', models.CharField(max_length=5)),
            ],
        ),
    ]
